/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PertemuanKelima;

import javax.swing.JOptionPane;

/**
 *
 * @author Rusdi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hasilNama1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        labelTtl = new javax.swing.JLabel();
        labelJenis = new javax.swing.JLabel();
        textTtl = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        labelNama2 = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        hasilAlamat = new javax.swing.JLabel();
        hasilTtl = new javax.swing.JLabel();
        labelNama3 = new javax.swing.JLabel();
        labelNama4 = new javax.swing.JLabel();
        cbJK = new javax.swing.JComboBox<>();
        labelAlamat2 = new javax.swing.JLabel();
        labelJk = new javax.swing.JLabel();
        hasilJk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("HOMEPAGE");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nama :");

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });

        labelTtl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelTtl.setText("TTL :");

        labelJenis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelJenis.setText("Jenis Kelamin : ");

        textTtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTtlActionPerformed(evt);
            }
        });

        textAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlamatActionPerformed(evt);
            }
        });

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        labelNama2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelNama2.setText("NAMA :");

        labelAlamat1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelAlamat1.setText("Alamat :");

        hasilAlamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        hasilTtl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        labelNama3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelNama3.setText("TTL :");

        labelNama4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        cbJK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Wanita" }));
        cbJK.setSelectedIndex(-1);
        cbJK.setToolTipText("Pilih Jenis Kelamin");
        cbJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJKActionPerformed(evt);
            }
        });

        labelAlamat2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelAlamat2.setText("Alamat :");

        labelJk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelJk.setText("JK");

        hasilJk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout hasilNama1Layout = new javax.swing.GroupLayout(hasilNama1);
        hasilNama1.setLayout(hasilNama1Layout);
        hasilNama1Layout.setHorizontalGroup(
            hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilNama1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilNama1Layout.createSequentialGroup()
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTtl)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hasilNama1Layout.createSequentialGroup()
                                .addComponent(textTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnSubmit))))
                    .addGroup(hasilNama1Layout.createSequentialGroup()
                        .addComponent(labelJenis)
                        .addGap(18, 18, 18)
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hasilNama1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilNama1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hasilNama1Layout.createSequentialGroup()
                                .addComponent(labelNama2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNama4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 19, Short.MAX_VALUE))
                            .addGroup(hasilNama1Layout.createSequentialGroup()
                                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlamat1)
                                    .addComponent(labelNama3))
                                .addGap(28, 28, 28)
                                .addComponent(hasilTtl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilNama1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(labelJk, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(hasilJk, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasilAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(106, 106, 106))
            .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hasilNama1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(labelAlamat2)
                    .addContainerGap(854, Short.MAX_VALUE)))
        );
        hasilNama1Layout.setVerticalGroup(
            hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilNama1Layout.createSequentialGroup()
                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilNama1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hasilNama1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama2)
                            .addComponent(labelNama4))))
                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilNama1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTtl)
                            .addComponent(textTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit)
                            .addComponent(labelNama3))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilNama1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hasilTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat1))
                .addGap(42, 42, 42)
                .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJenis))
                    .addComponent(hasilAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJk)
                    .addComponent(hasilJk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(hasilNama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hasilNama1Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(labelAlamat2)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasilNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hasilNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void textTtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTtlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTtlActionPerformed

    private void textAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlamatActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        
        
        hasilTtl.setText(textTtl.getText());
        hasilAlamat.setText(textAlamat.getText());
        
        if (cbJK.getSelectedIndex()==0) {
            hasilJk.setText(cbJK.getSelectedItem().toString());
        }
        if (cbJK.getSelectedIndex()==1) {
             hasilJk.setText(cbJK.getSelectedItem().toString());    
        }
        else if (cbJK.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "masukkan jenis kelamin !");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbJK;
    private javax.swing.JLabel hasilAlamat;
    private javax.swing.JLabel hasilJk;
    private javax.swing.JPanel hasilNama1;
    private javax.swing.JLabel hasilTtl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelAlamat2;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelJk;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelNama3;
    private javax.swing.JLabel labelNama4;
    private javax.swing.JLabel labelTtl;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textTtl;
    // End of variables declaration//GEN-END:variables
}
